<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EscolasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         // Desativa a verificação de chaves estrangeiras temporariamente
         DB::statement('SET FOREIGN_KEY_CHECKS=0;');
         DB::table('escolas')->truncate();
         DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        // Lista de escolas
        $escolas = [
            ['nome' => '02 DE JULHO', 'codigo_escola' => 'ESC001'],
            ['nome' => '15 DE JULHO', 'codigo_escola' => 'ESC002'],
            ['nome' => '25 DE JULHO', 'codigo_escola' => 'ESC003'],
            ['nome' => 'AMÉRICO TANURI - JUNCO', 'codigo_escola' => 'ESC004'],
            ['nome' => 'AMÉRICO TANURI - MANIÇOBA', 'codigo_escola' => 'ESC005'],
            ['nome' => 'ANÁLIA BARBOSA DE SOUZA', 'codigo_escola' => 'ESC006'],
            ['nome' => 'ANTONIO FRANCISCO DE OLIVEIRA', 'codigo_escola' => 'ESC007'],
            ['nome' => 'ARGEMIRO JOSE DA CRUZ', 'codigo_escola' => 'ESC008'],
            ['nome' => 'BOM JESUS - BARAÚNA', 'codigo_escola' => 'ESC009'],
            ['nome' => 'BOM JESUS - NH1', 'codigo_escola' => 'ESC010'],
            ['nome' => 'C.R.A. PROFª MAZZARELLO CAVALCANTI REIS DA ROCHA', 'codigo_escola' => 'ESC011'],
            ['nome' => 'CAIC - MISAEL AGUILAR', 'codigo_escola' => 'ESC012'],
            ['nome' => 'CAXANGÁ', 'codigo_escola' => 'ESC013'],
            ['nome' => 'CELSO CAVALCANTE DE CARVALHO', 'codigo_escola' => 'ESC014'],
            ['nome' => 'CENTRO SOCIAL URBANO - CSU', 'codigo_escola' => 'ESC015'],
            ['nome' => 'CORAÇÃO DE JESUS - JUREMA VERMELHA', 'codigo_escola' => 'ESC016'],
            ['nome' => 'CORAÇÃO DE JESUS - SERRA DA MADEIRA', 'codigo_escola' => 'ESC017'],
            ['nome' => 'DEPUTADO RAIMUNDO DA CUNHA LEITE', 'codigo_escola' => 'ESC018'],
            ['nome' => 'DOM AVELAR BRANDAO VILELA', 'codigo_escola' => 'ESC019'],
            ['nome' => 'DOUTOR EDSON RIBEIRO', 'codigo_escola' => 'ESC020'],
            ['nome' => 'DURVAL BARBOSA DA CUNHA', 'codigo_escola' => 'ESC021'],
            ['nome' => 'E.M.E.I. ADELAIDE MOREIRA BISPO', 'codigo_escola' => 'ESC022'],
            ['nome' => 'E.M.E.I. ADJALVA FERREIRA LIMA', 'codigo_escola' => 'ESC023'],
            ['nome' => 'E.M.E.I. AMÉLIA BORGES', 'codigo_escola' => 'ESC024'],
            ['nome' => 'E.M.E.I. AMÉLIA DUARTE', 'codigo_escola' => 'ESC025'],
            ['nome' => 'E.M.E.I. AMÉRICO TANURY - ABÓBORA', 'codigo_escola' => 'ESC026'],
            ['nome' => 'E.M.E.I. ANA MARIA MORGADO CHAVES', 'codigo_escola' => 'ESC027'],
            ['nome' => 'E.M.E.I. ANNA HILDA LEITE FARIAS', 'codigo_escola' => 'ESC028'],
            ['nome' => 'E.M.E.I. ARCENIO JOSÉ DA SILVA', 'codigo_escola' => 'ESC029'],
            ['nome' => 'E.M.E.I. ARLINDA ALVES VARJÃO', 'codigo_escola' => 'ESC030'],
            ['nome' => 'E.M.E.I. BEATRIZ ANGÉLICA MOTA', 'codigo_escola' => 'ESC031'],
            ['nome' => 'E.M.E.I. BOLIVAR SANTANA', 'codigo_escola' => 'ESC032'],
            ['nome' => 'E.M.E.I. BOM JESUS DOS NAVEGANTES', 'codigo_escola' => 'ESC033'],
            ['nome' => 'E.M.E.I. CAIC MISAEL AGUILAR', 'codigo_escola' => 'ESC034'],
            ['nome' => 'E.M.E.I. DILMA CALMON DE OLIVEIRA', 'codigo_escola' => 'ESC035'],
            ['nome' => 'E.M.E.I. EDIVÂNIA SANTOS CARDOSO', 'codigo_escola' => 'ESC036'],
            ['nome' => 'E.M.E.I. ELEOTÉRIO SOUZA', 'codigo_escola' => 'ESC037'],
            ['nome' => 'E.M.E.I. FRANCISCO PEREIRA DOS SANTOS', 'codigo_escola' => 'ESC038'],
            ['nome' => 'E.M.E.I. GABRIELA DE JESUS', 'codigo_escola' => 'ESC039'],
            ['nome' => 'E.M.E.I. IRMÃ ADILSON', 'codigo_escola' => 'ESC040'],
            ['nome' => 'E.M.E.I. IRMÃO ADEÍLSON', 'codigo_escola' => 'ESC041'],
            ['nome' => 'E.M.E.I. LÍDIA MARIA NOGUEIRA', 'codigo_escola' => 'ESC042'],
            ['nome' => 'E.M.E.I. LUIZ DE FREITAS', 'codigo_escola' => 'ESC043'],
            ['nome' => 'E.M.E.I. MARIA HELENA DA SILVA PEREIRA', 'codigo_escola' => 'ESC044'],
            ['nome' => 'E.M.E.I. MARIA HOZANA NUNES', 'codigo_escola' => 'ESC045'],
            ['nome' => 'E.M.E.I. MARIA JÚLIA RODRIGUES TANURI', 'codigo_escola' => 'ESC046'],
            ['nome' => 'E.M.E.I. MARIA SUELY MEDRADO ARAÚJO', 'codigo_escola' => 'ESC047'],
            ['nome' => 'E.M.E.I. MARIÁ VIANA TANURI', 'codigo_escola' => 'ESC048'],
            ['nome' => 'E.M.E.I. NAILDE DE SOUZA COSTA', 'codigo_escola' => 'ESC049'],
            ['nome' => 'E.M.E.I. NÉLIA DE SOUZA COSTA', 'codigo_escola' => 'ESC050'],
            ['nome' => 'E.M.E.I. NOSSA SENHORA DAS GROTAS - CARNAÍBA', 'codigo_escola' => 'ESC051'],
            ['nome' => 'E.M.E.I. NOSSO SENHOR DOS AFLITOS', 'codigo_escola' => 'ESC052'],
            ['nome' => 'E.M.E.I. PASSAGEM DO SARGENTO', 'codigo_escola' => 'ESC053'],
            ['nome' => 'E.M.E.I. PASTOR MANOEL MARQUES DE SOUZA', 'codigo_escola' => 'ESC054'],
            ['nome' => 'E.M.E.I. PREFEITO APRÍGIO DUARTE', 'codigo_escola' => 'ESC055'],
            ['nome' => 'E.M.E.I. PROFª HELOISA HELENA BENEVIDES FARIAS', 'codigo_escola' => 'ESC056'],
            ['nome' => 'E.M.E.I. PROFª JOANA RAMOS', 'codigo_escola' => 'ESC057'],
            ['nome' => 'E.M.E.I. VANDA GUERRA', 'codigo_escola' => 'ESC058'],
            ['nome' => 'E.M.R.T.I. SÃO JOSÉ', 'codigo_escola' => 'ESC059'],
            ['nome' => 'E.M.T.I. PROFª IRACEMA PEREIRA DA PAIXÃO', 'codigo_escola' => 'ESC060'],
            ['nome' => 'EDUCANDÁRIO JOÃO XXIII', 'codigo_escola' => 'ESC061'],
            ['nome' => 'ELISEU SANTOS', 'codigo_escola' => 'ESC062'],
            ['nome' => 'ESTAÇÃO DO SABER JOSÉ CARLOS TANURI', 'codigo_escola' => 'ESC063'],
            ['nome' => 'EURÍDICE RIBEIRO VIANA', 'codigo_escola' => 'ESC064'],
            ['nome' => 'EXTENSAO - BOLIVAR SANTANA', 'codigo_escola' => 'ESC065'],
            ['nome' => 'EXTENSAO - E.M.E.I. GENTIL DAMASIO DO NASCIMENTO', 'codigo_escola' => 'ESC066'],
            ['nome' => 'EXTENSAO - E.M.E.I. MARIA VIANA TANURI', 'codigo_escola' => 'ESC067'],
            ['nome' => 'EXTENSAO - MARIA MONTEIRO BACELAR', 'codigo_escola' => 'ESC068'],
            ['nome' => 'EXTENSAO - PRESIDENTE TANCREDO NEVES', 'codigo_escola' => 'ESC069'],
            ['nome' => 'FAMÍLIA UNIDA', 'codigo_escola' => 'ESC070'],
            ['nome' => 'GRACIOSA XAVIER RAMOS GOMES', 'codigo_escola' => 'ESC071'],
            ['nome' => 'HELENA ARAÚJO PINHEIRO', 'codigo_escola' => 'ESC072'],
            ['nome' => 'HELENA CELESTINO MAGALHÃES', 'codigo_escola' => 'ESC073'],
            ['nome' => 'JATOBÁ', 'codigo_escola' => 'ESC074'],
            ['nome' => 'JOÃO DIAS FERREIRA', 'codigo_escola' => 'ESC075'],
            ['nome' => 'JOÃO NEVES DE ALMEIDA', 'codigo_escola' => 'ESC076'],
            ['nome' => 'JOCA DE SOUZA OLIVEIRA', 'codigo_escola' => 'ESC077'],
            ['nome' => 'JOSÉ DE AMORIM', 'codigo_escola' => 'ESC078'],
            ['nome' => 'JOSÉ DIAS CAVALCANTE', 'codigo_escola' => 'ESC079'],
            ['nome' => 'JOSÉ MACÊDO DE ARAÚJO', 'codigo_escola' => 'ESC080'],
            ['nome' => 'JOSÉ NOGUEIRA DE ALMEIDA', 'codigo_escola' => 'ESC081'],
            ['nome' => 'JOSÉ RAMOS BORGES', 'codigo_escola' => 'ESC082'],
            ['nome' => 'LUIZ EDUARDO RODRIGUES', 'codigo_escola' => 'ESC083'],
            ['nome' => 'MARCÍLIO JOSÉ DE SOUZA', 'codigo_escola' => 'ESC084'],
            ['nome' => 'MARIA JOSÉ FARIAS', 'codigo_escola' => 'ESC085'],
            ['nome' => 'MARIA JOSÉ SILVA DE ARAÚJO', 'codigo_escola' => 'ESC086'],
            ['nome' => 'MARIA LUIZA ARAÚJO', 'codigo_escola' => 'ESC087'],
            ['nome' => 'MARIA MONTEIRO BACELAR', 'codigo_escola' => 'ESC088'],
            ['nome' => 'MARIANA DE SOUZA PEREIRA', 'codigo_escola' => 'ESC089'],
            ['nome' => 'MARIZETE ARAÚJO DO NASCIMENTO', 'codigo_escola' => 'ESC090'],
            ['nome' => 'MATINHA DE ALMEIDA', 'codigo_escola' => 'ESC091'],
            ['nome' => 'MERCÊS RAMOS DE SOUZA', 'codigo_escola' => 'ESC092'],
            ['nome' => 'MARIA JULIA RODRIGUES TANURI', 'codigo_escola' => 'ESC093'],
            ['nome' => 'MARIA MONTEIRO BACELAR', 'codigo_escola' => 'ESC094'],
            ['nome' => 'MARIANO RODRIGUES DE SOUZA', 'codigo_escola' => 'ESC095'],
            ['nome' => 'MIGUEL ÂNGELO DE SOUZA', 'codigo_escola' => 'ESC096'],
            ['nome' => 'NOSSA SENHORA DAS GROTAS - BOQUEIRÃO', 'codigo_escola' => 'ESC097'],
            ['nome' => 'NOSSA SENHORA DAS GROTAS-SEDE', 'codigo_escola' => 'ESC098'],
            ['nome' => 'NOSSA SENHORA RAINHA DOS ANJOS', 'codigo_escola' => 'ESC099'],
            ['nome' => 'OSORIO TELES DE MENEZES', 'codigo_escola' => 'ESC100'],
            ['nome' => 'PAULO FREIRE', 'codigo_escola' => 'ESC101'],
            ['nome' => 'PAULO VI', 'codigo_escola' => 'ESC102'],
            ['nome' => 'PEDRO DIAS', 'codigo_escola' => 'ESC103'],
            ['nome' => 'PONTAL', 'codigo_escola' => 'ESC104'],
            ['nome' => 'PREFEITO APRÍGIO DUARTE', 'codigo_escola' => 'ESC105'],
            ['nome' => 'PRESIDENTE TANCREDO NEVES', 'codigo_escola' => 'ESC106'],
            ['nome' => 'PROFª ANTONILA DA FRANÇA CARDOSO', 'codigo_escola' => 'ESC107'],
            ['nome' => 'PROFª ATANILHA LUZ ARAÚJO', 'codigo_escola' => 'ESC108'],
            ['nome' => 'PROFª BERNADETE BRAGA', 'codigo_escola' => 'ESC109'],
            ['nome' => 'PROFª CARMEM COSTA SANTOS', 'codigo_escola' => 'ESC110'],
            ['nome' => 'PROFª CRENILDES LUIZ BRANDÃO', 'codigo_escola' => 'ESC111'],
            ['nome' => 'PROFª DINORAH ALBERNAZ MELO DA SILVA', 'codigo_escola' => 'ESC112'],
            ['nome' => 'PROFª EDUALDINA DAMÁSIO', 'codigo_escola' => 'ESC113'],
            ['nome' => 'PROFª GUIOMAR LUSTOSA RODRIGUES', 'codigo_escola' => 'ESC114'],
            ['nome' => 'PROFª HAYDÉE FONSECA FALCÃO', 'codigo_escola' => 'ESC115'],
            ['nome' => 'PROFª IRACY NUNES DA SILVA', 'codigo_escola' => 'ESC116'],
            ['nome' => 'PROFª LEOPOLDINA LEAL', 'codigo_escola' => 'ESC117'],
            ['nome' => 'PROFª MARIA DE LOURDES DUARTE', 'codigo_escola' => 'ESC118'],
            ['nome' => 'PROFª MARIA FRANCA PIRES', 'codigo_escola' => 'ESC119'],
            ['nome' => 'PROFª MARIA JOSÉ LIMA DA ROCHA', 'codigo_escola' => 'ESC120'],
            ['nome' => 'PROFª MATILDE COSTA MEDRADO', 'codigo_escola' => 'ESC121'],
            ['nome' => 'PROFª OSCARLINA TANURI', 'codigo_escola' => 'ESC122'],
            ['nome' => 'PROFª TEREZINHA FERREIRA DE OLIVEIRA', 'codigo_escola' => 'ESC123'],
            ['nome' => 'PROFº CARLOS DA COSTA SILVA', 'codigo_escola' => 'ESC124'],
            ['nome' => 'PROFº JOSÉ PEREIRA DA SILVA', 'codigo_escola' => 'ESC125'],
            ['nome' => 'PROFº LUIS CURSINO DA FRANÇA CARDOSO', 'codigo_escola' => 'ESC126'],
            ['nome' => 'PROFº PEDRO RAIMUNDO RODRIGUES REGO', 'codigo_escola' => 'ESC127'],
            ['nome' => 'PROMENOR', 'codigo_escola' => 'ESC128'],
            ['nome' => 'RAIMUNDO CLEMENTINO DE SOUZA', 'codigo_escola' => 'ESC129'],
            ['nome' => 'RAIMUNDO MEDRADO PRIMO', 'codigo_escola' => 'ESC130'],
            ['nome' => 'RURAL DE MASSAROCA - ERUM', 'codigo_escola' => 'ESC131'],
            ['nome' => 'SANTA INÊS', 'codigo_escola' => 'ESC132'],
            ['nome' => 'SANTA TEREZINHA', 'codigo_escola' => 'ESC133'],
            ['nome' => 'SANTO ANTÔNIO', 'codigo_escola' => 'ESC134'],
            ['nome' => 'SÃO FRANCISCO DE ASSIS - MULUNGÚ', 'codigo_escola' => 'ESC135'],
            ['nome' => 'SÃO FRANCISCO DE ASSIS - NH2', 'codigo_escola' => 'ESC136'],
            ['nome' => 'SÃO JOSÉ', 'codigo_escola' => 'ESC137'],
            ['nome' => 'SÃO SEBASTIÃO', 'codigo_escola' => 'ESC138'],
            ['nome' => 'VEREADOR AMADEUS DAMÁSIO', 'codigo_escola' => 'ESC139'],
        ];

        // Inserir escolas no banco de dados
        DB::table('escolas')->insert($escolas);
    }
}
